
const glossary = [
    {'ID': 1, 'Term': 'DevOps', 
    'Description': 'The term “DevOps” originates from the combination of two words— Development and Operations, two of the most important components of any software development cycle. DevOps can be defined as a software development practice, directed towards agile development and efficient delivery of high-quality software, which it achieves by automating and integrating several aspects of application development (programming, version control, etc.) and IT operations (testing, debugging, packaging, and deploying to production, etc.). ', 
    'References':'Sharma, A. (2021, November 16). What is Devops | A Comprehensive Guide to DevOps. Scaler Topics. https://www.scaler.com/topics/what-is-devops/'},
    {'ID': 2, 'Term': 'Continuous Development', 
    'Description': 'Continuous Development is a key aspect of DevOps that involves the continuous improvement and delivery of software. It is a software development practice that focuses on the constant delivery of code changes and updates in small, incremental stages. This approach enables developers to quickly test and validate their code changes, and then deliver them to users with greater speed and frequency.', 
    'References':'Sharma, A. (2021, November 16). What is Devops | A Comprehensive Guide to DevOps. Scaler Topics. https://www.scaler.com/topics/what-is-devops/'}, 
    {'ID': 3, 'Term': 'Continuous Integration', 
    'Description': 'Continuous Integration (CI) is a key practice in the DevOps approach to software development that involves the continuous merging of code changes into a central repository. The goal of CI is to enable developers to detect and address any issues in the code as early as possible before they become more costly and time-consuming to fix.',
    'References':'Sharma, A. (2021, November 16). What is Devops | A Comprehensive Guide to DevOps. Scaler Topics. https://www.scaler.com/topics/what-is-devops/'},
    {'ID': 4, 'Term': 'Continuous Testing', 
    'Description': 'Continuous Testing is a key aspect of DevOps that involves the ongoing and automated testing of software throughout the development process. It is a software development practice that aims to ensure that code changes are thoroughly tested, validated, and verified and that any issues are identified and resolved as early as possible in the development cycle.',
    'References':'Sharma, A. (2021, November 16). What is Devops | A Comprehensive Guide to DevOps. Scaler Topics. https://www.scaler.com/topics/what-is-devops/'},
    {'ID': 5, 'Term': 'Automated Delivery Pipeline', 
    'Description': 'The automated Delivery Pipeline is a critical component of DevOps that involves the automated and continuous delivery of software updates to production environments. It is a software delivery practice that enables teams to streamline the release process, reduce errors and downtime, and deliver updates more quickly and reliably.',
    'References':'Sharma, A. (2021, November 16). What is Devops | A Comprehensive Guide to DevOps. Scaler Topics. https://www.scaler.com/topics/what-is-devops/'},
    {'ID': 6, 'Term': 'Lead time for Code Change', 
    'Description': 'One of the critical DevOps metrics to track is lead time for changes. Not to be confused with cycle time (discussed below), lead time for changes is the length of time between when a code change is committed to the trunk branch and when it is in a deployable state. For example, when code passes all necessary pre-release tests. automated Delivery Pipeline is a critical component of DevOps that involves the automated and continuous delivery of software updates to production environments. It is a software delivery practice that enables teams to streamline the release process, reduce errors and downtime, and deliver updates more quickly and reliably.',
    'References':'Atlassian. (n.d.). 4 Key DevOps Metrics to Know. Atlassian. Retrieved July 19, 2023, from https://www.atlassian.com/devops/frameworks/devops-metrics#:~:text=Lead%20time%20for%20changes&text=Not%20to%20be%20confused%20with'},
    {'ID': 7, 'Term': 'Change Failure Rate', 
    'Description': 'The change failure rate is the percentage of code changes that require hot fixes or other remediation after production. This does not measure failures caught by testing and fixed before code is deployed.',
    'References':'Atlassian. (n.d.). 4 Key DevOps Metrics to Know. Atlassian. Retrieved July 19, 2023, from https://www.atlassian.com/devops/frameworks/devops-metrics#:~:text=Lead%20time%20for%20changes&text=Not%20to%20be%20confused%20with'},
    {'ID': 8, 'Term': 'Deployment Frequency', 
    'Description': 'Understanding the frequency of how often new code is deployed into production is critical to understanding DevOps success. Many practitioners use the term “delivery” to mean code changes that are released into a pre-production staging environment, and reserve “deployment” to refer to code changes that are released into production.',
    'References':'Atlassian. (n.d.). 4 Key DevOps Metrics to Know. Atlassian. Retrieved July 19, 2023, from https://www.atlassian.com/devops/frameworks/devops-metrics#:~:text=Lead%20time%20for%20changes&text=Not%20to%20be%20confused%20with'},
    {'ID': 9, 'Term': 'Mean Time to Recovery (MTTR)', 
    'Description': 'Mean time to recovery (MTTR) measures how long it takes to recover from a partial service interruption or total failure. This is an important metric to track, regardless of whether the interruption is the result of a recent deployment or an isolated system failure. ',
    'References':'Atlassian. (n.d.). 4 Key DevOps Metrics to Know. Atlassian. Retrieved July 19, 2023, from https://www.atlassian.com/devops/frameworks/devops-metrics#:~:text=Lead%20time%20for%20changes&text=Not%20to%20be%20confused%20with'},
    {'ID': 10, 'Term': 'Cycle Time Reports', 
    'Description': 'Cycle time reports allow project leads to establish a baseline for the development pipeline that can be used to evaluate future processes. When teams optimize for cycle time, developers typically have less work in progress and fewer inefficient workflows.',
    'References':'Atlassian. (n.d.). 4 Key DevOps Metrics to Know. Atlassian. Retrieved July 19, 2023, from https://www.atlassian.com/devops/frameworks/devops-metrics#:~:text=Lead%20time%20for%20changes&text=Not%20to%20be%20confused%20with'},
    {'ID': 11, 'Term': 'SDO - Software Delivery Performance', 
    'Description': 'The four metrics of software delivery performance can be considered in terms of throughput and stability. DORA team measure throughput using lead time for code changes (that is, time from code commit to release in production), and deployment frequency. They measure stability using time to restore a service after an incident and change failure rate. A fifth metric represents operational performance and is a measure of modern operational practices.',
    'References':'[1] “2022 Accelerate State of DevOps Report” Available: “https://services.google.com/fh/files/misc/2022_state_of_devops_report.pdf‌”'},
    {'ID': 12, 'Term': 'Burnout', 
    'Description': 'Burnout is a significant concern in any high-pressure work environment, including DevOps. DevOps culture emphasizes continuous delivery, automation, and collaboration, which can lead to long hours, tight deadlines, and high expectations.',
    'References':'[1] “2022 Accelerate State of DevOps Report” Available: “https://services.google.com/fh/files/misc/2022_state_of_devops_report.pdf‌”'},
     {'ID': 13, 'Term': 'DevOps Cycle', 
      'Description' : 'The DevOps cycle is presented in an infinite loop because feedback from the live product (software product) that is managed by Ops (operations team) will be continuously provided back to Dev (development team) to improve the product. The DevOps cycle includes the following phases such as plan, create, verify, preprod, release, configure and monitor [1][2][3]',
      'References':'[1] “Chapter 1: Defining the Reference Architecture for Enterprise DevOps - Enterprise DevOps for Architects [Book],” www.oreilly.com. https://learning.oreilly.com/library/view/enterprise-devops-for/9781801812153/B17492_01_ePub_RK.xhtml#_idParaDest-22 (accessed Aug. 03, 2022).‌ [2] Selenium, “SeleniumHQ Browser Automation,” www.selenium.dev, 2023. https://www.selenium.dev/‌ [3]“DevOps toolchain,” Wikipedia, Jun. 18, 2023. https://en.wikipedia.org/wiki/DevOps_toolchain'},
      {'ID': 14, 'Term': 'Plan phase', 
      'Description': 'Planning stage is an initial stage in which development teams plan and define the objectives, requirements, and scope of the initiative – including prioritise new features, functions & fixes release plans, KPIs, update release metrics. Feedback is crucial during this phase to ensure that all stakeholders included Business & Operations have a shared understanding of the initiative goals and expectations.  Tools used for automation: JIRA, Git, IDEs like VS Code, Figma.[1][2][3]',
      'References':'[1] “Chapter 1: Defining the Reference Architecture for Enterprise DevOps - Enterprise DevOps for Architects [Book],” www.oreilly.com. https://learning.oreilly.com/library/view/enterprise-devops-for/9781801812153/B17492_01_ePub_RK.xhtml#_idParaDest-22 (accessed Aug. 03, 2022).‌ [2] Selenium, “SeleniumHQ Browser Automation,” www.selenium.dev, 2023. https://www.selenium.dev/‌ [3]“DevOps toolchain,” Wikipedia, Jun. 18, 2023. https://en.wikipedia.org/wiki/DevOps_toolchain'},
     {'ID': 15, 'Term': 'Create phase', 
     'Description': 'In the create/build phase, the actual coding and development take place. During this phase developers also perform functional, code quality, and performance tests. In create phase, developers collaborate closely with operations and testing teams to ensure that the code is well-designed, maintainable, and follows best practices and established processes withing the organisation. Tools used for automation: Git, GitHub, Jenkins, bitbucket, SonarQube for code analysis. [1][2][3] ',
     'References':'[1] “Chapter 1: Defining the Reference Architecture for Enterprise DevOps - Enterprise DevOps for Architects [Book],” www.oreilly.com. https://learning.oreilly.com/library/view/enterprise-devops-for/9781801812153/B17492_01_ePub_RK.xhtml#_idParaDest-22 (accessed Aug. 03, 2022).‌ [2] Selenium, “SeleniumHQ Browser Automation,” www.selenium.dev, 2023. https://www.selenium.dev/‌ [3]“DevOps toolchain,” Wikipedia, Jun. 18, 2023. https://en.wikipedia.org/wiki/DevOps_toolchain'},
    {'ID': 16, 'Term': 'Verify phase', 
    'Description': 'Once the development is complete, the code moves to the testing phase. Here, automated testing and continuous integration tools are commonly used to detect bugs, errors, and other issues early in the development process. The feedback collected during testing (common tests types are - regression, acceptance, progression, performance, security) helps identify areas for improvement and provides insights into the overall quality of the code. During this stage various metrics like, pass & fail rates on each type of tests, defect density etc get collected. Tools used for automation: Junit, JMeter, Git, GitHub and automated test suites like Selenium [1][2][3].',
    'References':'[1] “Chapter 1: Defining the Reference Architecture for Enterprise DevOps - Enterprise DevOps for Architects [Book],” www.oreilly.com. https://learning.oreilly.com/library/view/enterprise-devops-for/9781801812153/B17492_01_ePub_RK.xhtml#_idParaDest-22 (accessed Aug. 03, 2022).‌ [2] Selenium, “SeleniumHQ Browser Automation,” www.selenium.dev, 2023. https://www.selenium.dev/‌ [3]“DevOps toolchain,” Wikipedia, Jun. 18, 2023. https://en.wikipedia.org/wiki/DevOps_toolchain'},
    {'ID': 17, 'Term': 'Preprod', 
    'Description': 'Preprod is a staging phase wherein tested code will be verified again for release readiness. After the verification/sanity tests, the release management seek the approval for production release.  Tools used for automation: Junit, JMeter, Git, GitHub and automated test suites like Selenium [1][2][3].',
    'References':'[1] “Chapter 1: Defining the Reference Architecture for Enterprise DevOps - Enterprise DevOps for Architects [Book],” www.oreilly.com. https://learning.oreilly.com/library/view/enterprise-devops-for/9781801812153/B17492_01_ePub_RK.xhtml#_idParaDest-22 (accessed Aug. 03, 2022).‌ [2] Selenium, “SeleniumHQ Browser Automation,” www.selenium.dev, 2023. https://www.selenium.dev/‌ [3]“DevOps toolchain,” Wikipedia, Jun. 18, 2023. https://en.wikipedia.org/wiki/DevOps_toolchain'},
    {'ID': 18, 'Term': 'Release', 
    'Description': 'At this phase the tested and release ready code will be applied to the production (auto deploy in automated CI/CD environments) in accordance with release plan. After deployment the status of the deployment will be provided to various stakeholders including development and operations team stakeholders. If the production deployment not successful, the fallback or recovery actions performance in accordance with the release plan. Tools used for automation: AWS CloudFormation, Azure Resource Manager.[1][2][3]',
    'References':'[1] “Chapter 1: Defining the Reference Architecture for Enterprise DevOps - Enterprise DevOps for Architects [Book],” www.oreilly.com. https://learning.oreilly.com/library/view/enterprise-devops-for/9781801812153/B17492_01_ePub_RK.xhtml#_idParaDest-22 (accessed Aug. 03, 2022).‌ [2] Selenium, “SeleniumHQ Browser Automation,” www.selenium.dev, 2023. https://www.selenium.dev/‌ [3]“DevOps toolchain,” Wikipedia, Jun. 18, 2023. https://en.wikipedia.org/wiki/DevOps_toolchain'},
    {'ID': 19, 'Term': 'Configure', 
    'Description': 'This phase is optional in some scenarios. At this phase if any infrastructure changes including storage, database and network will be performed. This will be done in accordance with the design artefacts and developers advice. The necessary configuration details will be part of the release plan. [1][2][3]',
    'References':'[1] “Chapter 1: Defining the Reference Architecture for Enterprise DevOps - Enterprise DevOps for Architects [Book],” www.oreilly.com. https://learning.oreilly.com/library/view/enterprise-devops-for/9781801812153/B17492_01_ePub_RK.xhtml#_idParaDest-22 (accessed Aug. 03, 2022).‌ [2] Selenium, “SeleniumHQ Browser Automation,” www.selenium.dev, 2023. https://www.selenium.dev/‌ [3]“DevOps toolchain,” Wikipedia, Jun. 18, 2023. https://en.wikipedia.org/wiki/DevOps_toolchain'},
    {'ID': 20, 'Term': 'Monitor', 
    'Description': 'Operations team start monitor the applicant/product performance and availability. Operations team also evaluate and record end users response and experiences as well. Tools used: Splunk or customized monitoring and log writing. [1][2][3]',
    'References':'[1] “Chapter 1: Defining the Reference Architecture for Enterprise DevOps - Enterprise DevOps for Architects [Book],” www.oreilly.com. https://learning.oreilly.com/library/view/enterprise-devops-for/9781801812153/B17492_01_ePub_RK.xhtml#_idParaDest-22 (accessed Aug. 03, 2022).‌ [2] Selenium, “SeleniumHQ Browser Automation,” www.selenium.dev, 2023. https://www.selenium.dev/‌ [3]“DevOps toolchain,” Wikipedia, Jun. 18, 2023. https://en.wikipedia.org/wiki/DevOps_toolchain'},
    {'ID': 21, 'Term': 'Node.js', 
    'Description':'Node.js represents a versatile, open-source server environment that possesses cross-platform compatibility, functioning seamlessly on a range of operating systems such as Windows, Linux, Unix, and macOS. Operating as a backend JavaScript runtime environment, Node.js operates atop the V8 JavaScript engine, enabling the execution of JavaScript code outside the confines of a web browser.',
    'References':'[1]“Node.js,” Wikipedia, Mar. 13, 2020. https://en.wikipedia.org/wiki/Node.js'},
    {'ID': 22, 'Term': 'Express.js', 
    'Description':'Express, often referred to as Express.js, stands as a backend web application framework tailored for constructing RESTful APIs using Node.js. This software is freely available and open-source, operating under the MIT License. Express has been meticulously crafted for the development of web applications and APIs, and it holds the distinction of being widely recognized as the standard server framework for Node.js',
    'References':'[1] “Express.js,” Wikipedia, Mar. 07, 2020. https://en.wikipedia.org/wiki/Express.js'},
    {'ID': 23, 'Term': 'npm', 
    'Description':'npm serves as the default package manager for the Node.js JavaScript runtime environment. Comprising both a command line client referred to as npm and an online repository housing both public and private packages, known as the npm registry, it offers a comprehensive ecosystem. npm, Inc. maintains npm as a package manager designed for the JavaScript programming language.',
    'References':'[1]“NPM,” Wikipedia, Apr. 15, 2022. https://en.wikipedia.org/wiki/Npm'},
    {'ID': 24, 'Term': 'passport.js', 
    'Description':'Passport.js stands out as a widely used middleware designed for Node.js, streamlining the intricate tasks associated with incorporating authentication and authorization within web applications. This middleware provides support for an array of strategies, including but not limited to local, OAuth, OpenID, and JWT, and seamlessly integrates with MongoDB and Mongoose for a seamless experience.',
    'References':'[1] “What are the benefits and drawbacks of using passport.js for authentication in web apps?,” www.linkedin.com. https://www.linkedin.com/advice/0/what-benefits-drawbacks-using-passportjs-authentication#:~:text=Aug%203%2C%202023- (accessed Aug. 18, 2023).'},
    {'ID': 25, 'Term': 'socket.io', 
    'Description':'Socket.IO serves as a real-time communication library tailored for Node.js, facilitating two-way event-driven communication linking the server and the client. Its capabilities make it an ideal choice for applications like chat platforms, real-time analytics, and beyond.',
    'References':'[1]“Socket.IO,” Wikipedia, Jun. 25, 2022. https://en.wikipedia.org/wiki/Socket.IO'},
    {'ID': 26, 'Term': 'async.js', 
    'Description':'The async function declaration establishes an association between a fresh async function and a designated name. Inside the function body, the await keyword is permissible, allowing the composition of asynchronous, promise-based operations in a more concise manner and eliminating the necessity of explicitly setting up promise chains.',
    'References':'[1]“async function - JavaScript | MDN,” developer.mozilla.org. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function'},
    {'ID': 27, 'Term': 'nodemon.io', 
    'Description':'Nodemon serves as a tool that keeps a watchful eye on alterations in your source code and, in the course of development, takes care of automatically restarting your Node.js application. This convenient feature spares you the effort of having to manually reboot the server each time modifications are made.',
    'References':'.....'},
    {'ID': 28, 'Term': 'dotenv', 
    'Description':'Dotenv Npm, an open-source Node module, streamlines the handling of environment variables, tools, and configurations within Node.js applications. This module empowers developers to generate distinct environment files tailored to various development phases and contexts. This approach ensures that pertinent settings for each unique environment are stored, administered, and conveniently retrievable.',
    'References':'[1]“Dotenv Npm: Npm Explained,” Bito, Apr. 05, 2023. https://bito.ai/resources/dotenv-npm-npm-explained/ (accessed Aug. 18, 2023).'},
    {'ID': 29, 'Term': 'Containerization', 
    'Description':'software engineering, containerization refers to the practice of employing either operating system-level virtualization or application-level virtualization across multiple network resources. This allows software applications to execute within segregated user environments, referred to as containers. These containers offer isolation and can function within diverse environments, irrespective of whether they are cloud-based or non-cloud, and regardless of the specific type or provider.',
    'References':'[1]“Containerization (computing),” Wikipedia, Mar. 14, 2022. https://en.wikipedia.org/wiki/Containerization_(computing)'},
    {'ID': 30, 'Term': 'Docker', 
    'Description':'Docker encompasses a collection of platform as a service offerings utilizing OS-level virtualization to distribute software within compact units known as containers. This service is available in both complimentary and premium tiers. The software responsible for managing these containers is referred to as Docker Engine. Its initial release dates back to 2013, and its ongoing development is undertaken by Docker, Inc.',
    'References':'[1]Wikipedia Contributors, “Docker (software),” Wikipedia, Nov. 16, 2019. https://en.wikipedia.org/wiki/Docker_(software)'}
    ,{'ID': 31, 'Term': 'Docker Container', 
    'Description':'A lightweight, standalone, and executable package that includes everything needed to run a piece of software, including the code, runtime, libraries, and system tools.',
    'References':'“Glossary,” Docker Documentation, Dec. 11, 2020. https://docs.docker.com/glossary/‌'}
    ,{'ID': 32, 'Term': 'Docker Image', 
    'Description':'A read-only template used to create containers. Its a snapshot of a file system that contains application code, libraries, and dependencies.',
    'References':'“Glossary,” Docker Documentation, Dec. 11, 2020. https://docs.docker.com/glossary/'}
    ,{'ID': 34, 'Term': 'Dockerfile', 
    'Description':'A text file that contains instructions for building a Docker image. It specifies the base image, application code, dependencies, and configurations.',
    'References':'“Glossary,” Docker Documentation, Dec. 11, 2020. https://docs.docker.com/glossary/'}
    ,{'ID': 35, 'Term': 'Docker Hub', 
    'Description':'A cloud-based registry service where you can find and share Docker images. Its a central repository for Docker images.',
    'References':'“Glossary,” Docker Documentation, Dec. 11, 2020. https://docs.docker.com/glossary/'}
    ,{'ID': 36, 'Term': 'Docker Registry', 
    'Description':'A storage and content delivery system for Docker images. Docker Hub is a public registry, but you can also set up private registries.',
    'References':'“Glossary,” Docker Documentation, Dec. 11, 2020. https://docs.docker.com/glossary/'}
    ,{'ID': 37, 'Term': 'Docker Volume', 
    'Description':'A Docker feature that allows data to persist beyond the lifetime of a container. Volumes are used for storing and sharing data between containers and the host.',
    'References':'“Glossary,” Docker Documentation, Dec. 11, 2020. https://docs.docker.com/glossary/'}
    ,{'ID': 38, 'Term': 'Docker Compose', 
    'Description':'A tool for defining and running multi-container Docker applications. It uses a YAML file to define services, networks, and volumes.',
    'References':'“Glossary,” Docker Documentation, Dec. 11, 2020. https://docs.docker.com/glossary/'}
    ,{'ID': 39, 'Term': 'Docker Swarm', 
    'Description':'Docker Swarm is a native clustering and orchestration solution for Docker. It allows you to create and manage a swarm of Docker nodes.',
    'References':'“Glossary,” Docker Documentation, Dec. 11, 2020. https://docs.docker.com/glossary/'}
    ,{'ID': 40, 'Term': 'Kubernetes (K8s)', 
    'Description':'A powerful open-source container orchestration platform used for automating the deployment, scaling, and management of containerized applications.',
    'References':'“Kubernetes,” Wikipedia, May 11, 2020. https://en.wikipedia.org/wiki/Kubernetes‌'}];

    module.exports = glossary;

