var express = require('express');
var router = express.Router();


const glossary = [
  {'ID': 1, 'Term': 'DevOps', 
  'Description': 'The term “DevOps” originates from the combination of two words— Development and Operations, two of the most important components of any software development cycle. DevOps can be defined as a software development practice, directed towards agile development and efficient delivery of high-quality software, which it achieves by automating and integrating several aspects of application development (programming, version control, etc.) and IT operations (testing, debugging, packaging, and deploying to production, etc.). ', 
  'References':'Sharma, A. (2021, November 16). What is Devops | A Comprehensive Guide to DevOps. Scaler Topics. https://www.scaler.com/topics/what-is-devops/'},
  {'ID': 2, 'Term': 'Continuous Development', 
  'Description': 'Continuous Development is a key aspect of DevOps that involves the continuous improvement and delivery of software. It is a software development practice that focuses on the constant delivery of code changes and updates in small, incremental stages. This approach enables developers to quickly test and validate their code changes, and then deliver them to users with greater speed and frequency.', 
  'References':'Sharma, A. (2021, November 16). What is Devops | A Comprehensive Guide to DevOps. Scaler Topics. https://www.scaler.com/topics/what-is-devops/'}, 
  {'ID': 3, 'Term': 'Continuous Integration', 
  'Description': 'Continuous Integration (CI) is a key practice in the DevOps approach to software development that involves the continuous merging of code changes into a central repository. The goal of CI is to enable developers to detect and address any issues in the code as early as possible before they become more costly and time-consuming to fix.',
  'References':'Sharma, A. (2021, November 16). What is Devops | A Comprehensive Guide to DevOps. Scaler Topics. https://www.scaler.com/topics/what-is-devops/'},
  {'ID': 4, 'Term': 'Continuous Testing', 
  'Description': 'Continuous Testing is a key aspect of DevOps that involves the ongoing and automated testing of software throughout the development process. It is a software development practice that aims to ensure that code changes are thoroughly tested, validated, and verified and that any issues are identified and resolved as early as possible in the development cycle.',
  'References':'Sharma, A. (2021, November 16). What is Devops | A Comprehensive Guide to DevOps. Scaler Topics. https://www.scaler.com/topics/what-is-devops/'},
  {'ID': 5, 'Term': 'Automated Delivery Pipeline', 
  'Description': 'The automated Delivery Pipeline is a critical component of DevOps that involves the automated and continuous delivery of software updates to production environments. It is a software delivery practice that enables teams to streamline the release process, reduce errors and downtime, and deliver updates more quickly and reliably.',
  'References':'Sharma, A. (2021, November 16). What is Devops | A Comprehensive Guide to DevOps. Scaler Topics. https://www.scaler.com/topics/what-is-devops/'},
  {'ID': 6, 'Term': 'Lead time for Code Change', 
  'Description': 'One of the critical DevOps metrics to track is lead time for changes. Not to be confused with cycle time (discussed below), lead time for changes is the length of time between when a code change is committed to the trunk branch and when it is in a deployable state. For example, when code passes all necessary pre-release tests. automated Delivery Pipeline is a critical component of DevOps that involves the automated and continuous delivery of software updates to production environments. It is a software delivery practice that enables teams to streamline the release process, reduce errors and downtime, and deliver updates more quickly and reliably.',
  'References':'Atlassian. (n.d.). 4 Key DevOps Metrics to Know. Atlassian. Retrieved July 19, 2023, from https://www.atlassian.com/devops/frameworks/devops-metrics#:~:text=Lead%20time%20for%20changes&text=Not%20to%20be%20confused%20with'},
  {'ID': 7, 'Term': 'Change Failure Rate', 
  'Description': 'The change failure rate is the percentage of code changes that require hot fixes or other remediation after production. This does not measure failures caught by testing and fixed before code is deployed.',
  'References':'Atlassian. (n.d.). 4 Key DevOps Metrics to Know. Atlassian. Retrieved July 19, 2023, from https://www.atlassian.com/devops/frameworks/devops-metrics#:~:text=Lead%20time%20for%20changes&text=Not%20to%20be%20confused%20with'},
  {'ID': 8, 'Term': 'Deployment Frequency', 
  'Description': 'Understanding the frequency of how often new code is deployed into production is critical to understanding DevOps success. Many practitioners use the term “delivery” to mean code changes that are released into a pre-production staging environment, and reserve “deployment” to refer to code changes that are released into production.',
  'References':'Atlassian. (n.d.). 4 Key DevOps Metrics to Know. Atlassian. Retrieved July 19, 2023, from https://www.atlassian.com/devops/frameworks/devops-metrics#:~:text=Lead%20time%20for%20changes&text=Not%20to%20be%20confused%20with'},
  {'ID': 9, 'Term': 'Mean Time to Recovery (MTTR)', 
  'Description': 'Mean time to recovery (MTTR) measures how long it takes to recover from a partial service interruption or total failure. This is an important metric to track, regardless of whether the interruption is the result of a recent deployment or an isolated system failure. ',
  'References':'Atlassian. (n.d.). 4 Key DevOps Metrics to Know. Atlassian. Retrieved July 19, 2023, from https://www.atlassian.com/devops/frameworks/devops-metrics#:~:text=Lead%20time%20for%20changes&text=Not%20to%20be%20confused%20with'},
  {'ID': 10, 'Term': 'Cycle Time Reports', 
  'Description': 'Cycle time reports allow project leads to establish a baseline for the development pipeline that can be used to evaluate future processes. When teams optimize for cycle time, developers typically have less work in progress and fewer inefficient workflows.',
  'References':'Atlassian. (n.d.). 4 Key DevOps Metrics to Know. Atlassian. Retrieved July 19, 2023, from https://www.atlassian.com/devops/frameworks/devops-metrics#:~:text=Lead%20time%20for%20changes&text=Not%20to%20be%20confused%20with'},
  {'ID': 11, 'Term': 'SDO - Software Delivery Performance', 
  'Description': 'The four metrics of software delivery performance can be considered in terms of throughput and stability. DORA team measure throughput using lead time for code changes (that is, time from code commit to release in production), and deployment frequency. They measure stability using time to restore a service after an incident and change failure rate. A fifth metric represents operational performance and is a measure of modern operational practices.',
  'References':'[1] “2022 Accelerate State of DevOps Report” Available: “https://services.google.com/fh/files/misc/2022_state_of_devops_report.pdf‌”'},
  {'ID': 12, 'Term': 'Burnout', 
  'Description': 'Burnout is a significant concern in any high-pressure work environment, including DevOps. DevOps culture emphasizes continuous delivery, automation, and collaboration, which can lead to long hours, tight deadlines, and high expectations.',
  'References':'[1] “2022 Accelerate State of DevOps Report” Available: “https://services.google.com/fh/files/misc/2022_state_of_devops_report.pdf‌”'},
   {'ID': 13, 'Term': 'DevOps Cycle', 
    'Description' : 'The DevOps cycle is presented in an infinite loop because feedback from the live product (software product) that is managed by Ops (operations team) will be continuously provided back to Dev (development team) to improve the product. The DevOps cycle includes the following phases such as plan, create, verify, preprod, release, configure and monitor [1][2][3]',
    'References':'[1] “Chapter 1: Defining the Reference Architecture for Enterprise DevOps - Enterprise DevOps for Architects [Book],” www.oreilly.com. https://learning.oreilly.com/library/view/enterprise-devops-for/9781801812153/B17492_01_ePub_RK.xhtml#_idParaDest-22 (accessed Aug. 03, 2022).‌ [2] Selenium, “SeleniumHQ Browser Automation,” www.selenium.dev, 2023. https://www.selenium.dev/‌ [3]“DevOps toolchain,” Wikipedia, Jun. 18, 2023. https://en.wikipedia.org/wiki/DevOps_toolchain'},
    {'ID': 14, 'Term': 'Plan phase', 
    'Description': 'Planning stage is an initial stage in which development teams plan and define the objectives, requirements, and scope of the initiative – including prioritise new features, functions & fixes release plans, KPIs, update release metrics. Feedback is crucial during this phase to ensure that all stakeholders included Business & Operations have a shared understanding of the initiative goals and expectations.  Tools used for automation: JIRA, Git, IDEs like VS Code, Figma.[1][2][3]',
    'References':'[1] “Chapter 1: Defining the Reference Architecture for Enterprise DevOps - Enterprise DevOps for Architects [Book],” www.oreilly.com. https://learning.oreilly.com/library/view/enterprise-devops-for/9781801812153/B17492_01_ePub_RK.xhtml#_idParaDest-22 (accessed Aug. 03, 2022).‌ [2] Selenium, “SeleniumHQ Browser Automation,” www.selenium.dev, 2023. https://www.selenium.dev/‌ [3]“DevOps toolchain,” Wikipedia, Jun. 18, 2023. https://en.wikipedia.org/wiki/DevOps_toolchain'},
   {'ID': 15, 'Term': 'Create phase', 
   'Description': 'In the create/build phase, the actual coding and development take place. During this phase developers also perform functional, code quality, and performance tests. In create phase, developers collaborate closely with operations and testing teams to ensure that the code is well-designed, maintainable, and follows best practices and established processes withing the organisation. Tools used for automation: Git, GitHub, Jenkins, bitbucket, SonarQube for code analysis. [1][2][3] ',
   'References':'[1] “Chapter 1: Defining the Reference Architecture for Enterprise DevOps - Enterprise DevOps for Architects [Book],” www.oreilly.com. https://learning.oreilly.com/library/view/enterprise-devops-for/9781801812153/B17492_01_ePub_RK.xhtml#_idParaDest-22 (accessed Aug. 03, 2022).‌ [2] Selenium, “SeleniumHQ Browser Automation,” www.selenium.dev, 2023. https://www.selenium.dev/‌ [3]“DevOps toolchain,” Wikipedia, Jun. 18, 2023. https://en.wikipedia.org/wiki/DevOps_toolchain'},
  {'ID': 16, 'Term': 'Verify phase', 
  'Description': 'Once the development is complete, the code moves to the testing phase. Here, automated testing and continuous integration tools are commonly used to detect bugs, errors, and other issues early in the development process. The feedback collected during testing (common tests types are - regression, acceptance, progression, performance, security) helps identify areas for improvement and provides insights into the overall quality of the code. During this stage various metrics like, pass & fail rates on each type of tests, defect density etc get collected. Tools used for automation: Junit, JMeter, Git, GitHub and automated test suites like Selenium [1][2][3].',
  'References':'[1] “Chapter 1: Defining the Reference Architecture for Enterprise DevOps - Enterprise DevOps for Architects [Book],” www.oreilly.com. https://learning.oreilly.com/library/view/enterprise-devops-for/9781801812153/B17492_01_ePub_RK.xhtml#_idParaDest-22 (accessed Aug. 03, 2022).‌ [2] Selenium, “SeleniumHQ Browser Automation,” www.selenium.dev, 2023. https://www.selenium.dev/‌ [3]“DevOps toolchain,” Wikipedia, Jun. 18, 2023. https://en.wikipedia.org/wiki/DevOps_toolchain'},
  {'ID': 17, 'Term': 'Preprod', 
  'Description': 'Preprod is a staging phase wherein tested code will be verified again for release readiness. After the verification/sanity tests, the release management seek the approval for production release.  Tools used for automation: Junit, JMeter, Git, GitHub and automated test suites like Selenium [1][2][3].',
  'References':'[1] “Chapter 1: Defining the Reference Architecture for Enterprise DevOps - Enterprise DevOps for Architects [Book],” www.oreilly.com. https://learning.oreilly.com/library/view/enterprise-devops-for/9781801812153/B17492_01_ePub_RK.xhtml#_idParaDest-22 (accessed Aug. 03, 2022).‌ [2] Selenium, “SeleniumHQ Browser Automation,” www.selenium.dev, 2023. https://www.selenium.dev/‌ [3]“DevOps toolchain,” Wikipedia, Jun. 18, 2023. https://en.wikipedia.org/wiki/DevOps_toolchain'},
  {'ID': 18, 'Term': 'Release', 
  'Description': 'At this phase the tested and release ready code will be applied to the production (auto deploy in automated CI/CD environments) in accordance with release plan. After deployment the status of the deployment will be provided to various stakeholders including development and operations team stakeholders. If the production deployment not successful, the fallback or recovery actions performance in accordance with the release plan. Tools used for automation: AWS CloudFormation, Azure Resource Manager.[1][2][3]',
  'References':'[1] “Chapter 1: Defining the Reference Architecture for Enterprise DevOps - Enterprise DevOps for Architects [Book],” www.oreilly.com. https://learning.oreilly.com/library/view/enterprise-devops-for/9781801812153/B17492_01_ePub_RK.xhtml#_idParaDest-22 (accessed Aug. 03, 2022).‌ [2] Selenium, “SeleniumHQ Browser Automation,” www.selenium.dev, 2023. https://www.selenium.dev/‌ [3]“DevOps toolchain,” Wikipedia, Jun. 18, 2023. https://en.wikipedia.org/wiki/DevOps_toolchain'},
  {'ID': 19, 'Term': 'Configure', 
  'Description': 'This phase is optional in some scenarios. At this phase if any infrastructure changes including storage, database and network will be performed. This will be done in accordance with the design artefacts and developers advice. The necessary configuration details will be part of the release plan. [1][2][3]',
  'References':'[1] “Chapter 1: Defining the Reference Architecture for Enterprise DevOps - Enterprise DevOps for Architects [Book],” www.oreilly.com. https://learning.oreilly.com/library/view/enterprise-devops-for/9781801812153/B17492_01_ePub_RK.xhtml#_idParaDest-22 (accessed Aug. 03, 2022).‌ [2] Selenium, “SeleniumHQ Browser Automation,” www.selenium.dev, 2023. https://www.selenium.dev/‌ [3]“DevOps toolchain,” Wikipedia, Jun. 18, 2023. https://en.wikipedia.org/wiki/DevOps_toolchain'},
  {'ID': 20, 'Term': 'Monitor', 
  'Description': 'Operations team start monitor the applicant/product performance and availability. Operations team also evaluate and record end users response and experiences as well. Tools used: Splunk or customized monitoring and log writing. [1][2][3]',
  'References':'[1] “Chapter 1: Defining the Reference Architecture for Enterprise DevOps - Enterprise DevOps for Architects [Book],” www.oreilly.com. https://learning.oreilly.com/library/view/enterprise-devops-for/9781801812153/B17492_01_ePub_RK.xhtml#_idParaDest-22 (accessed Aug. 03, 2022).‌ [2] Selenium, “SeleniumHQ Browser Automation,” www.selenium.dev, 2023. https://www.selenium.dev/‌ [3]“DevOps toolchain,” Wikipedia, Jun. 18, 2023. https://en.wikipedia.org/wiki/DevOps_toolchain'},
 ];


/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'SIT722 DevOps Glossary', sub: 'Welcome to my Website showing a collection of DevOps Terms and brief description', glossary:glossary });
});

module.exports = router;
